# -*- coding: utf-8 -*-
"""ApacheSpark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hwb-4-IzgGX__ViUHYATGlZmxAyU7eIP

**Instalação do Apache Spark**
"""

!pip install pyspark

#donwload do arquivo utilizando o gdown
!pip install gdown

file_id = '1c-6vJHDVsYt6TVr8QZADTLN_KgoDM45E'
destination = '/content/imoveis.csv'

# Baixar o arquivo CSV
import gdown
gdown.download(f'https://drive.google.com/uc?id={file_id}', destination, quiet=False)

# Verificar se o arquivo foi baixado com sucesso
!ls /content
# Exibir o esquema dos dados
df.printSchema()

#Criação da Sessão Spark
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("HousePricePrediction").getOrCreate()

df = spark.read.csv('/content/imoveis.csv', header=True, inferSchema=True)

df.show(15)

"""Importação das funções SQL"""

from pyspark.sql.functions import count, when, col
from pyspark.sql import functions as F

"""**Realização de comandos SQL na base com ApacheSpark**



"""

#Contagem das tuplas
df.count()

# Exibe estatísticas como média, desvio padrão, mínimo e máximo para as colunas numéricas
df.describe().show()

# Seleciona e exibe as colunas "bedrooms", "bathrooms" e "price"
df.select("bedrooms", "bathrooms", "price").show(5)

# Filtra e exibe imóveis com 3 quartos
df.filter(df["bedrooms"] == 3).show(5)
# Filtra imóveis com preço acima de $500k e mais de 2 banheiros
df.filter((df["price"] > 500000) & (df["bathrooms"] > 2)).show(5)

# Agrupa por "zipcode" e calcula a média dos preços
df.groupBy("zipcode").avg("price").show(5)
# Conta o número de imóveis agrupados pela coluna "waterfront" (se possui vista para água ou não)
df.groupBy("waterfront").count().show()

# Agrupa por número de quartos e exibe a média, máximo e mínimo de preço
df.groupBy("bedrooms").agg(
    F.avg("price").alias("avg_price"),
    F.max("price").alias("max_price"),
    F.min("price").alias("min_price")
).show(10)

# Exemplo de agregação avançada com múltiplas funções
df.groupBy("bedrooms").agg(
    F.count("price").alias("total_properties"),  # Conta o número de propriedades
    F.avg("price").alias("avg_price"),           # Calcula a média de preço
    F.sum("sqft_living").alias("total_sqft"),    # Soma a área total
    F.max("price").alias("max_price"),           # Obtém o preço máximo
    F.min("price").alias("min_price")            # Obtém o preço mínimo
).show()

""" **Preparação do Dataframe para treinamento do modelo com Regressão Linear**


"""

#Contagem de entradas NULL presentes no Dataframe.
df.select([count(when(col(c).isNull(), c)).alias(c) for c in df.columns]).show()
#Não foram encrontadas entradas Null

#Remoção de colunas irrelevantes para o modelo
df = df.drop('id', 'date' )

df.select([count(when(col(c).isNull(), c)).alias(c) for c in df.columns]).show()

df.show(15)

# Remover outliers usando o intervalo interquartil
from pyspark.sql.functions import col, expr

# Definindo o IQR para detecção de outliers
q1, q3 = df.approxQuantile("price", [0.25, 0.75], 0.05)
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

# Filtrando os outliers
df_filtered = df.filter((df.price >= lower_bound) & (df.price <= upper_bound))

# Selecionar as features relevantes
df_filtered = df_filtered.select("bedrooms", "bathrooms", "sqft_living", "sqft_lot", "floors",
                                 "waterfront", "view", "condition", "grade", "sqft_above",
                                 "sqft_basement", "yr_built", "yr_renovated", "zipcode",
                                 "lat", "long", "sqft_living15", "sqft_lot15", "price")
df_filtered.show(5)

#Separeação dos dados de treino e de teste
train_data, test_data = df_filtered.randomSplit([0.8, 0.2], seed=45)
train_data.show(5)
test_data.show(5)

# Importar bibliotecas necessárias
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.regression import LinearRegression

# Transformar as features em um vetor de características
assembler = VectorAssembler(inputCols=["bedrooms", "bathrooms", "sqft_living", "sqft_lot", "floors",
                                       "waterfront", "view", "condition", "grade", "sqft_above",
                                       "sqft_basement", "yr_built", "yr_renovated", "zipcode",
                                       "lat", "long", "sqft_living15", "sqft_lot15"], outputCol="features")

# Transformar os dados
train_data_assembled = assembler.transform(train_data)
test_data_assembled = assembler.transform(test_data)

# Criar o modelo de regressão linear
lr = LinearRegression(featuresCol='features', labelCol='price')

# Treinar o modelo
lr_model = lr.fit(train_data_assembled)

# Avaliar o modelo
test_results = lr_model.evaluate(test_data_assembled)
print(f"MAE: {test_results.meanAbsoluteError}")
print(f"R2: {test_results.r2}")

# Fazer previsões no conjunto de teste
predictions = lr_model.transform(test_data_assembled)

# Exibir as previsões
predictions.select("prediction", "price", "features").show(5)

"""O modelo apresentou R² de 69% de explicabilidade das projeções e um MAE de $86.165 dolares, fiz tentativas de transformações logaritmas nos dados e procurei mudar o tamanho das bases de de treino e teste , mas o resultado se manteve abaixo de R²69%.

**Tentativa de avaliar a correlação com o Heatmap .**
"""

# Importar as bibliotecas necessárias
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Converter os dados filtrados de Spark para Pandas
pandas_df = df_filtered.toPandas()

# Verificar as primeiras linhas
pandas_df.head()

# Gerar a matriz de correlação
correlation_matrix = pandas_df.corr()

# Plotar o Heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title("Heatmap de Correlações")
plt.show()

"""**A propriedade Price mostrou fraca correlação com a maioria das outras entradas, com isso o modelo de Regressão linear pode não ser um bom modelo para este dataframe.**"""